///////////////////////////////////////////////////////////////////////////////
// Module: aurora_top_tb
// Description: Testbench for dual Aurora 64B66B top-level module
//              (Streaming mode).
//
// This testbench provides:
//   1. Clock and reset generation
//   2. Loopback connection between Channel 0 TX and Channel 1 RX (and vice versa)
//   3. aurora_data_gen module instances for TX data generation
//   4. RX data monitoring and verification
//
// Note: This testbench is for behavioral simulation only. The Aurora 64B66B
//       IP core must be available (generated by Vivado) for the simulation
//       to work. For standalone testing without the IP core, the Aurora IP
//       instantiation in aurora_channel.v would need to be replaced with
//       a behavioral model.
///////////////////////////////////////////////////////////////////////////////

`timescale 1ns / 1ps

module aurora_top_tb;

    //=========================================================================
    // Parameters
    //=========================================================================
    parameter DATA_WIDTH = 256;
    parameter LANE_NUM   = 4;

    // Clock periods
    parameter GT_REFCLK_PERIOD = 6.206;     // ~161.13 MHz GT reference clock
    parameter INIT_CLK_PERIOD  = 10.000;    // 100 MHz init clock

    //=========================================================================
    // Signal declarations
    //=========================================================================
    // System
    reg                         init_clk_in;
    reg                         sys_rst_n;

    // GT Reference Clock
    reg                         gt_refclk_p;
    wire                        gt_refclk_n;

    // Channel 0 GT Serial
    wire [LANE_NUM-1:0]         ch0_rxp;
    wire [LANE_NUM-1:0]         ch0_rxn;
    wire [LANE_NUM-1:0]         ch0_txp;
    wire [LANE_NUM-1:0]         ch0_txn;

    // Channel 1 GT Serial
    wire [LANE_NUM-1:0]         ch1_rxp;
    wire [LANE_NUM-1:0]         ch1_rxn;
    wire [LANE_NUM-1:0]         ch1_txp;
    wire [LANE_NUM-1:0]         ch1_txn;

    // Channel 0 TX (from data gen)
    wire [DATA_WIDTH-1:0]       ch0_tx_din;
    wire                        ch0_tx_din_valid;
    wire                        ch0_tx_ready;

    // Channel 1 TX (from data gen)
    wire [DATA_WIDTH-1:0]       ch1_tx_din;
    wire                        ch1_tx_din_valid;
    wire                        ch1_tx_ready;

    // Channel 0 RX
    wire [DATA_WIDTH-1:0]       ch0_rx_dout;
    wire                        ch0_rx_dout_valid;

    // Channel 1 RX
    wire [DATA_WIDTH-1:0]       ch1_rx_dout;
    wire                        ch1_rx_dout_valid;

    // Status
    wire                        ch0_channel_up;
    wire [LANE_NUM-1:0]         ch0_lane_up;
    wire                        ch0_hard_err;
    wire                        ch0_soft_err;
    wire                        ch1_channel_up;
    wire [LANE_NUM-1:0]         ch1_lane_up;
    wire                        ch1_hard_err;
    wire                        ch1_soft_err;

    wire                        user_clk_out;

    // Test counters
    integer                     rx_ch0_count;
    integer                     rx_ch1_count;
    integer                     error_count;

    //=========================================================================
    // Clock Generation
    //=========================================================================
    // GT Reference Clock (differential)
    initial gt_refclk_p = 1'b0;
    always #(GT_REFCLK_PERIOD / 2) gt_refclk_p = ~gt_refclk_p;
    assign gt_refclk_n = ~gt_refclk_p;

    // Init Clock
    initial init_clk_in = 1'b0;
    always #(INIT_CLK_PERIOD / 2) init_clk_in = ~init_clk_in;

    //=========================================================================
    // GT Serial Loopback
    //
    // Connect Channel 0 TX to Channel 1 RX and vice versa for testing.
    //=========================================================================
    assign ch0_rxp = ch1_txp;       // Channel 0 receives from Channel 1
    assign ch0_rxn = ch1_txn;
    assign ch1_rxp = ch0_txp;       // Channel 1 receives from Channel 0
    assign ch1_rxn = ch0_txn;

    //=========================================================================
    // Data Generation Module - Channel 0
    //
    // Generates incrementing 32-bit pattern for Channel 0 TX.
    //=========================================================================
    aurora_data_gen #(
        .DATA_WIDTH                 (DATA_WIDTH)
    ) u_data_gen_ch0 (
        .user_clk                   (user_clk_out),
        .reset                      (~sys_rst_n),
        .channel_up                 (ch0_channel_up),
        .tx_ready                   (ch0_tx_ready),
        .tx_data                    (ch0_tx_din),
        .tx_valid                   (ch0_tx_din_valid)
    );

    //=========================================================================
    // Data Generation Module - Channel 1
    //
    // Generates incrementing 32-bit pattern for Channel 1 TX.
    //=========================================================================
    aurora_data_gen #(
        .DATA_WIDTH                 (DATA_WIDTH)
    ) u_data_gen_ch1 (
        .user_clk                   (user_clk_out),
        .reset                      (~sys_rst_n),
        .channel_up                 (ch1_channel_up),
        .tx_ready                   (ch1_tx_ready),
        .tx_data                    (ch1_tx_din),
        .tx_valid                   (ch1_tx_din_valid)
    );

    //=========================================================================
    // DUT Instantiation
    //=========================================================================
    aurora_top #(
        .DATA_WIDTH                 (DATA_WIDTH),
        .LANE_NUM                   (LANE_NUM)
    ) u_dut (
        // System
        .init_clk_in                (init_clk_in),
        .sys_rst_n                  (sys_rst_n),

        // GT Reference Clock
        .gt_refclk_p                (gt_refclk_p),
        .gt_refclk_n                (gt_refclk_n),

        // Channel 0 GT Serial
        .ch0_rxp                    (ch0_rxp),
        .ch0_rxn                    (ch0_rxn),
        .ch0_txp                    (ch0_txp),
        .ch0_txn                    (ch0_txn),

        // Channel 1 GT Serial
        .ch1_rxp                    (ch1_rxp),
        .ch1_rxn                    (ch1_rxn),
        .ch1_txp                    (ch1_txp),
        .ch1_txn                    (ch1_txn),

        // Channel 0 TX (Streaming)
        .ch0_tx_din                 (ch0_tx_din),
        .ch0_tx_din_valid           (ch0_tx_din_valid),
        .ch0_tx_ready               (ch0_tx_ready),

        // Channel 1 TX (Streaming)
        .ch1_tx_din                 (ch1_tx_din),
        .ch1_tx_din_valid           (ch1_tx_din_valid),
        .ch1_tx_ready               (ch1_tx_ready),

        // Channel 0 RX (Streaming)
        .ch0_rx_dout                (ch0_rx_dout),
        .ch0_rx_dout_valid          (ch0_rx_dout_valid),

        // Channel 1 RX (Streaming)
        .ch1_rx_dout                (ch1_rx_dout),
        .ch1_rx_dout_valid          (ch1_rx_dout_valid),

        // Status
        .ch0_channel_up             (ch0_channel_up),
        .ch0_lane_up                (ch0_lane_up),
        .ch0_hard_err               (ch0_hard_err),
        .ch0_soft_err               (ch0_soft_err),
        .ch1_channel_up             (ch1_channel_up),
        .ch1_lane_up                (ch1_lane_up),
        .ch1_hard_err               (ch1_hard_err),
        .ch1_soft_err               (ch1_soft_err),

        .user_clk_out               (user_clk_out)
    );

    //=========================================================================
    // Reset Sequence and Test Control
    //=========================================================================
    initial begin
        // Initialize
        sys_rst_n    = 1'b0;
        rx_ch0_count = 0;
        rx_ch1_count = 0;
        error_count  = 0;

        // Hold reset for 200 ns
        #200;
        sys_rst_n = 1'b1;
        $display("[%0t] INFO: System reset de-asserted", $time);

        // Wait for both channels to come up
        $display("[%0t] INFO: Waiting for both channels to be up...", $time);
        wait (ch0_channel_up && ch1_channel_up);
        $display("[%0t] INFO: Both channels are UP!", $time);
        $display("[%0t] INFO:   Channel 0 lane_up = %b", $time, ch0_lane_up);
        $display("[%0t] INFO:   Channel 1 lane_up = %b", $time, ch1_lane_up);
        $display("[%0t] INFO: Data generators are now streaming...", $time);

        // Let data stream for 1000 clock cycles
        repeat (1000) @(posedge user_clk_out);

        // Report results
        $display("");
        $display("============================================");
        $display("  Test Results");
        $display("============================================");
        $display("  CH0 RX beats received: %0d", rx_ch0_count);
        $display("  CH1 RX beats received: %0d", rx_ch1_count);
        $display("  Errors:                %0d", error_count);
        $display("============================================");
        $display("");

        if (error_count == 0 && rx_ch0_count > 0 && rx_ch1_count > 0) begin
            $display("TEST PASSED");
        end else begin
            $display("TEST FAILED");
        end

        $finish;
    end

    //=========================================================================
    // RX Data Monitoring
    //
    // Count and display received data on both channels.
    // Shows the 32-bit field [31:0] to verify incrementing pattern.
    //=========================================================================
    always @(posedge user_clk_out) begin
        if (ch0_rx_dout_valid) begin
            rx_ch0_count = rx_ch0_count + 1;
            if (rx_ch0_count <= 10) begin  // Print first 10 beats
                $display("[%0t] CH0 RX [beat %0d]: [31:0]=0x%08h [63:32]=0x%08h [95:64]=0x%08h [127:96]=0x%08h [159:128]=0x%08h [191:160]=0x%08h [223:192]=0x%08h [255:224]=0x%08h",
                         $time, rx_ch0_count,
                         ch0_rx_dout[ 31:  0], ch0_rx_dout[ 63: 32],
                         ch0_rx_dout[ 95: 64], ch0_rx_dout[127: 96],
                         ch0_rx_dout[159:128], ch0_rx_dout[191:160],
                         ch0_rx_dout[223:192], ch0_rx_dout[255:224]);
            end
        end

        if (ch1_rx_dout_valid) begin
            rx_ch1_count = rx_ch1_count + 1;
            if (rx_ch1_count <= 10) begin  // Print first 10 beats
                $display("[%0t] CH1 RX [beat %0d]: [31:0]=0x%08h [63:32]=0x%08h [95:64]=0x%08h [127:96]=0x%08h [159:128]=0x%08h [191:160]=0x%08h [223:192]=0x%08h [255:224]=0x%08h",
                         $time, rx_ch1_count,
                         ch1_rx_dout[ 31:  0], ch1_rx_dout[ 63: 32],
                         ch1_rx_dout[ 95: 64], ch1_rx_dout[127: 96],
                         ch1_rx_dout[159:128], ch1_rx_dout[191:160],
                         ch1_rx_dout[223:192], ch1_rx_dout[255:224]);
            end
        end
    end

    //=========================================================================
    // Error Monitoring
    //=========================================================================
    always @(posedge user_clk_out) begin
        if (ch0_hard_err) begin
            $display("[%0t] ERROR: Channel 0 hard error!", $time);
            error_count = error_count + 1;
        end
        if (ch0_soft_err) begin
            $display("[%0t] WARNING: Channel 0 soft error", $time);
        end
        if (ch1_hard_err) begin
            $display("[%0t] ERROR: Channel 1 hard error!", $time);
            error_count = error_count + 1;
        end
        if (ch1_soft_err) begin
            $display("[%0t] WARNING: Channel 1 soft error", $time);
        end
    end

    //=========================================================================
    // Channel Up/Down Monitoring
    //=========================================================================
    always @(ch0_channel_up) begin
        if (ch0_channel_up)
            $display("[%0t] INFO: Channel 0 is UP", $time);
        else if ($time > 0)
            $display("[%0t] WARNING: Channel 0 went DOWN", $time);
    end

    always @(ch1_channel_up) begin
        if (ch1_channel_up)
            $display("[%0t] INFO: Channel 1 is UP", $time);
        else if ($time > 0)
            $display("[%0t] WARNING: Channel 1 went DOWN", $time);
    end

    //=========================================================================
    // Simulation timeout
    //=========================================================================
    initial begin
        #10_000_000;    // 10 ms timeout
        $display("[%0t] ERROR: Simulation timeout!", $time);
        $finish;
    end

    //=========================================================================
    // Waveform dump (optional, for debugging)
    //=========================================================================
    initial begin
        $dumpfile("aurora_top_tb.vcd");
        $dumpvars(0, aurora_top_tb);
    end

endmodule
