///////////////////////////////////////////////////////////////////////////////
// Module: aurora_gt_common_wrapper
// Description: GTHE2_COMMON (QPLL) wrapper for Aurora 64B66B.
//              Each GT quad requires one GTHE2_COMMON instance.
//              When two Aurora cores on adjacent banks share a reference clock,
//              each bank still needs its own GTHE2_COMMON, but both use the
//              same reference clock input from a single IBUFDS_GTE2.
//
// Note: QPLL parameters below are typical for Aurora 64B66B at 10.3125 Gbps.
//       Verify these parameters against the Aurora IP example design output
//       generated by Vivado for your specific line rate configuration.
///////////////////////////////////////////////////////////////////////////////

`timescale 1ns / 1ps

module aurora_gt_common_wrapper (
    // Reference clock
    input  wire         gt_refclk,          // GT reference clock (from IBUFDS_GTE2)

    // QPLL reset
    input  wire         qpll_reset,         // QPLL reset (from Aurora core or external)

    // QPLL outputs to Aurora core
    output wire         qpll_outclk,        // QPLL output clock
    output wire         qpll_outrefclk,     // QPLL output reference clock
    output wire         qpll_lock,          // QPLL lock indicator
    output wire         qpll_refclklost,    // QPLL reference clock lost

    // DRP interface for GT Common
    input  wire         drp_clk,            // DRP clock
    input  wire [7:0]   drp_addr,           // DRP address
    input  wire [15:0]  drp_di,             // DRP data input
    output wire [15:0]  drp_do,             // DRP data output
    input  wire         drp_en,             // DRP enable
    output wire         drp_rdy,            // DRP ready
    input  wire         drp_we              // DRP write enable
);

    //=========================================================================
    // Internal signals
    //=========================================================================
    wire    qpll_fb_clk;                    // QPLL feedback clock (internal)

    //=========================================================================
    // GTHE2_COMMON instantiation
    //
    // This primitive provides the QPLL (Quad PLL) for a GT quad.
    // Parameters are set for typical Aurora 64B66B operation.
    // In a real design, copy the exact parameters from the Aurora IP
    // example design generated by Vivado.
    //=========================================================================
    GTHE2_COMMON #(
        // Simulation attributes
        .SIM_RESET_SPEEDUP          ("TRUE"),
        .SIM_QPLLREFCLK_SEL        (3'b001),
        .SIM_VERSION                ("2.0"),

        // QPLL configuration
        .QPLL_CFG                   (27'h04801C7),
        .QPLL_CLKOUT_CFG           (4'b1111),
        .QPLL_COARSE_FREQ_OVRD     (6'b010000),
        .QPLL_COARSE_FREQ_OVRD_EN  (1'b0),
        .QPLL_CP                    (10'b0000011111),
        .QPLL_CP_MONITOR_EN        (1'b0),
        .QPLL_DMONITOR_SEL          (1'b0),
        .QPLL_FBDIV                 (10'b0101000000),
        .QPLL_FBDIV_MONITOR_EN      (1'b0),
        .QPLL_FBDIV_RATIO           (1'b0),
        .QPLL_INIT_CFG              (24'h000006),
        .QPLL_LOCK_CFG              (16'h05E8),
        .QPLL_LPF                   (4'b1111),
        .QPLL_REFCLK_DIV            (1),

        // Common block attributes
        .BIAS_CFG                   (64'h0000040000001050),
        .COMMON_CFG                 (32'h00000000),
        .RSVD_ATTR0                 (16'h0000),
        .RSVD_ATTR1                 (16'h0000)
    )
    gthe2_common_inst (
        // QPLL clock outputs
        .QPLLOUTCLK                 (qpll_outclk),
        .QPLLOUTREFCLK              (qpll_outrefclk),

        // QPLL feedback
        .QPLLFBCLKLOST              (),
        .QPLLLOCK                   (qpll_lock),
        .QPLLREFCLKLOST             (qpll_refclklost),

        // QPLL reset
        .QPLLRESET                  (qpll_reset),
        .QPLLLOCKDETCLK             (drp_clk),
        .QPLLLOCKEN                 (1'b1),
        .QPLLOUTRESET               (1'b0),
        .QPLLPD                     (1'b0),

        // Reference clock selection
        .QPLLREFCLKSEL              (3'b001),       // MGTREFCLK0
        .GTGREFCLK                  (1'b0),
        .GTNORTHREFCLK0             (1'b0),
        .GTNORTHREFCLK1             (1'b0),
        .GTSOUTHREFCLK0             (1'b0),
        .GTSOUTHREFCLK1             (1'b0),
        .GTREFCLK0                  (gt_refclk),
        .GTREFCLK1                  (1'b0),

        // DRP interface
        .DRPCLK                     (drp_clk),
        .DRPADDR                    (drp_addr),
        .DRPDI                      (drp_di),
        .DRPDO                      (drp_do),
        .DRPEN                      (drp_en),
        .DRPRDY                     (drp_rdy),
        .DRPWE                      (drp_we),

        // Reserved
        .BGBYPASSB                  (1'b1),
        .BGMONITORENB               (1'b1),
        .BGPDB                      (1'b1),
        .BGRCALOVRD                 (5'b11111),
        .BGRCALOVRDENB              (1'b1),
        .RCALENB                    (1'b1),
        .PMARSVD                    (8'b0),
        .REFCLKOUTMONITOR           ()
    );

endmodule
